apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mail-dev2
  namespace: argo-cd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: dev2
    server: https://kubernetes.default.svc
  project: default
  source:
    path: mailpit
    repoURL: https://github.com/Yannig/argocd-example.git
    targetRevision: v1.0.0
